# Application Configuration
spring.application.name = AuthSpringbootSecurity

# Server Configurations
server.port = 8080
#server.servlet.context-path = /api

# Database Connections
# Connection Details
spring.datasource.url = jdbc:postgresql://localhost:5432/dmart_db
spring.datasource.username = dmart_user
spring.datasource.password = Siddarth@28

# Spring Data JPA Configuration
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.use_sql_comments = true
spring.jpa.properties.hibernate.format_sql=true


# JWT Configuration
jwt.secret = ${JWT_SECRET:QZ3G8mOoEpHgA1jQ1+752Q/C2L5Rw02jzHgbGqPBWzI=}
jwt.expiration = 900000
jwt.refresh.expiration = 604800000

